title: "C++ - STL - new features C++17"
description: "C++ Blog"
baseurl: ""
url: "https://VerenaG.github.io"
exclude: ["LICENSE", "Remarks.md"]
github_username: ["VerenaG"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
